In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("./heart_failure_clinical_records_dataset.csv")


df.head(5)

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [6]:
df = df.rename(columns={"DEATH_EVENT":"class"})

In [8]:
df.shape

(299, 13)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
 12  class                     299 non-null    int64  
dtypes: float64(3), int64(10)
memory usage: 30.5 KB


In [10]:
df.describe().T

count           mean           std      min  \
age                       299.0      60.833893     11.894809     40.0   
anaemia                   299.0       0.431438      0.496107      0.0   
creatinine_phosphokinase  299.0     581.839465    970.287881     23.0   
diabetes                  299.0       0.418060      0.494067      0.0   
ejection_fraction         299.0      38.083612     11.834841     14.0   
high_blood_pressure       299.0       0.351171      0.478136      0.0   
platelets                 299.0  263358.029264  97804.236869  25100.0   
serum_creatinine          299.0       1.393880      1.034510      0.5   
serum_sodium              299.0     136.625418      4.412477    113.0   
sex                       299.0       0.648829      0.478136      0.0   
smoking                   299.0       0.321070      0.467670      0.0   
time                      299.0     130.260870     77.614208      4.0   
class                     299.0       0.321070      0.467670      0.0   

                               25%       50%       75%       max  
age                           51.0      60.0      70.0      95.0  
anaemia                        0.0       0.0       1.0       1.0  
creatinine_phosphokinase     116.5     250.0     582.0    7861.0  
diabetes                       0.0       0.0       1.0       1.0  
ejection_fraction             30.0      38.0      45.0      80.0  
high_blood_pressure            0.0       0.0       1.0       1.0  
platelets                 212500.0  262000.0  303500.0  850000.0  
serum_creatinine               0.9       1.1       1.4       9.4  
serum_sodium                 134.0     137.0     140.0     148.0  
sex                            0.0       1.0       1.0       1.0  
smoking                        0.0       0.0       1.0       1.0  
time                          73.0     115.0     203.0     285.0  
class                          0.0       0.0       1.0       1.0

In [11]:
df.corr()["class"]
to_drop = ['diabetes', 'sex', 'smoking', 'class', 'creatinine_phosphokinase ']

age                         0.253729
anaemia                     0.066270
creatinine_phosphokinase    0.062728
diabetes                   -0.001943
ejection_fraction          -0.268603
high_blood_pressure         0.079351
platelets                  -0.049139
serum_creatinine            0.294278
serum_sodium               -0.195204
sex                        -0.004316
smoking                    -0.012623
time                       -0.526964
class                       1.000000
Name: class, dtype: float64

In [25]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

scaler = MinMaxScaler()

X = scaler.fit_transform(df.drop(['diabetes','class'], axis=1))
y = df["class"]

smote = SMOTE(random_state=42)
X_sampled, y_sampled = smote.fit_resample(X, y)


X_train, X_test, y_train , y_test = train_test_split(X_sampled, y_sampled, test_size=0.1, random_state=42)

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix


models = [LogisticRegression(random_state=42), SVC(random_state=42), KNeighborsClassifier(), RandomForestClassifier(random_state=42),DecisionTreeClassifier(random_state=42)]


for model in models:
    name = model.__class__.__name__
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print("Mode: ", name)
    print("Accuracy: ", accuracy_score(y_test, y_pred))
    print("Precision: ", precision_score(y_test, y_pred))
    print("Recall: ", recall_score(y_test, y_pred))
    print("F1 Score: ", f1_score(y_test, y_pred))
    print("Confusion matrix: \n", confusion_matrix(y_test, y_pred))
    print("-----------------------------------------------------------")


Mode:  LogisticRegression
Accuracy:  0.7073170731707317
Precision:  0.6666666666666666
Recall:  0.6666666666666666
F1 Score:  0.6666666666666666
Confusion matrix: 
 [[17  6]
 [ 6 12]]
-----------------------------------------------------------
Mode:  SVC
Accuracy:  0.7804878048780488
Precision:  0.7368421052631579
Recall:  0.7777777777777778
F1 Score:  0.7567567567567568
Confusion matrix: 
 [[18  5]
 [ 4 14]]
-----------------------------------------------------------
Mode:  KNeighborsClassifier
Accuracy:  0.7317073170731707
Precision:  0.6521739130434783
Recall:  0.8333333333333334
F1 Score:  0.7317073170731707
Confusion matrix: 
 [[15  8]
 [ 3 15]]
-----------------------------------------------------------
Mode:  RandomForestClassifier
Accuracy:  0.8536585365853658
Precision:  0.8
Recall:  0.8888888888888888
F1 Score:  0.8421052631578947
Confusion matrix: 
 [[19  4]
 [ 2 16]]
-----------------------------------------------------------
Mode:  DecisionTreeClassifier
Accuracy:  0.80487

In [28]:
from sklearn.ensemble import RandomForestClassifier

best_model = RandomForestClassifier(random_state=42)
best_model.fit(X_train, y_train)

y_pred_train = best_model.predict(X_train)
y_pred = best_model.predict(X_test)

print("Training")
print("Accuracy: ", accuracy_score(y_train, y_pred_train))
print("Precision: ", precision_score(y_train, y_pred_train))
print("Recall: ", recall_score(y_train, y_pred_train))
print("F1 Score: ", f1_score(y_train, y_pred_train))
print("Confusion matrix: \n", confusion_matrix(y_train, y_pred_train))
print("-----------------------------------------------")

print("Testing")
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("F1 Score: ", f1_score(y_test, y_pred))
print("Confusion matrix: \n", confusion_matrix(y_test, y_pred))

Training
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1 Score:  1.0
Confusion matrix: 
 [[180   0]
 [  0 185]]
-----------------------------------------------
Testing
Accuracy:  0.8536585365853658
Precision:  0.8
Recall:  0.8888888888888888
F1 Score:  0.8421052631578947
Confusion matrix: 
 [[19  4]
 [ 2 16]]
